EXECUTE IMMEDIATE FROM './STG_ASSET_CREATE.sql';
EXECUTE IMMEDIATE FROM './STG_USER_CREATE.sql';
EXECUTE IMMEDIATE FROM './STG_CASE_CREATE.sql';
EXECUTE IMMEDIATE FROM './STG_CONTACT_CREATE.sql';
EXECUTE IMMEDIATE FROM './DM_ASSET_CREATE.sql';
EXECUTE IMMEDIATE FROM './DM_USER_CREATE.sql';
EXECUTE IMMEDIATE FROM './DM_CASE_CREATE.sql';
EXECUTE IMMEDIATE FROM './DM_CONTACT_CREATE.sql';
